---
title: '<div>General Developer How-tos (Gen Dev)</div>'
output:
  html_document:
    toc: FALSE
    toc_depth: 3
    toc_float:
    collapsed: false
---

<table class="table">
  <!--
  *
  * DQD Example
  *
  * -->
  <tr>
    <td>Run/Debug R-code Example</td>
    <td>
      <a href="developer-how-tos_gen_dev_dqd_example.html">Data Quality Dashboard Example</a>
      <br/>
        This document provides a complete example of how to 
        <ul>
          <li>Download, install, and run Broadsea (including the Eunomia test CDM)</li>
          <li>Fork, create a branch, clone, and check out the Data Quality Dashboard from GitHub</li>
          <li>Install your local copy of the Data Quality Dashboard as the DataQualityDashboard R-Library</li>
          <li>Use the SosRunDataQualityDashboard project to configure, run, and debug Data Quality Dashboard</li>
        </ul>
    </td>
  </tr>
  <!--
  *
  * Install GitHub Token
  *
  * -->
  <tr>
    <td>Install GitHub Token in R</td>
    <td>
      Many of the OHDSI R projects will require multiple installs from GitHub. 
      GitHub allows for installs as is but only up to a certian limit if you do not have a GitHub token installed in your R environment. 
      If this limit is exceeded, installs will fail and you won't have a good time. 
      Instructions for installing the R token are available at 
      <a href="https://ohdsi.github.io/DatabaseOnSpark/developer-how-tos_gen_dev.html">https://ohdsi.github.io/DatabaseOnSpark/developer-how-tos_gen_dev.html</a>. 
      The process is basically this:
      <ul>
        <li>
          Create the token in GitHub (the token does not require any of the permissions listed, so leave all the checkboxes unchecked) 
          <a href="https://github.com/settings/tokens">https://github.com/settings/tokens</a>. 
        </li>
        <li>
          Edit the .Renviron file by running the following
<pre class="r">
install.packages("usethis")
library(usethis)
edit_r_environ()
</pre>
          Add the following line to your .Renviron file (where @MY_TOKEN is the token you just created).
        </li>
<pre class="r">
GITHUB_PAT = '@MY_TOKEN'
</pre>
      </ul>
    </td>
  </tr>
  <!--
  *
  * Store Password in keyring
  *
  * -->
  <tr>
    <td>Store Passwords/Tokens in keyring in R</td>
    <td>
      <a href="developer-how-tos_gen_dev_keyring.html">Data Quality Dashboard Example</a>
      <br/>
        This document provides a complete example of how to 
        <ul>
          <li>Download, install, and run Broadsea (including the Eunomia test CDM)</li>
          <li>Fork, create a branch, clone, and check out the Data Quality Dashboard from GitHub</li>
          <li>Install your local copy of the Data Quality Dashboard as the DataQualityDashboard R-Library</li>
          <li>Use the SosRunDataQualityDashboard project to configure, run, and debug Data Quality Dashboard</li>
        </ul>
    </td>
  </tr>
  <!--
  *
  * Blank Line
  *
  * -->
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>