---
title: '<div>How to checkout, run, debug, and contribute to Data Quality Dashboard</div>'
output:
  html_document:
    toc: FALSE
    toc_depth: 3
    toc_float:
    collapsed: false
---

<!--
*
* Introduction
*
-->
<h3>Introduction</h3>
This document provides a complete example of how to 
<ul>
  <li>Download, install, and run Broadsea (including the Eunomia test CDM)</li>
  <li>Fork, create a branch, clone, and check out the Data Quality Dashboard from GitHub</li>
  <li>Install your local copy of the Data Quality Dashboard as the DataQualityDashboard R-Library</li>
  <li>Use the SosRunDataQualityDashboard project to configure, run, and debug Data Quality Dashboard</li>
</ul>

<!--
*
* Broadsea
*
-->
<h3>Broadsea</h3>
<p>
  Broadsea is a complete solution for running OHDSI tools that runs in a 
  <a href="https://www.docker.com/">Docker</a> container. 
  Complete instructions for installing and running Broadsea are here: 
  <a href="developer-how-tos_gen_dev_broadsea.html">Install and Run Broadsea</a>
</p>

<!--
*
* Download SosRunDataqualityDashbosard
*
-->
<h3>Download and Initialize the SosRunDataQualityDashboard project</h3>
<p>
  The SosRunDataQualityDashboard provides some simple scripts that can be used to: 
  <ul>
    <li>Install the R libraries required for DQD</li>
    <li>Create the configuration to run DQD</li>
    <li>Run DQD</li>
    <li>View the results of DQD</li>
  </ul>
  <p>
  Clone the SosRunDataQualityDashboard using the following:
<pre class="pre-scrollable">
git clone https://github.com/NACHC-CAD/SosRunDataQualityDashboard
</pre>  
  </p>
</p>



