---
title: '<div>OHDSI Databricks User Group: Developer How-tos</div>'
output:
  html_document:
    toc: FALSE
    toc_depth: 3
    toc_float:
    collapsed: false
---

<h2>Developer How-tos</h2>

<table class="table">
  <!--
  *
  * How to Add to this Documentation
  *
  * -->
  <tr>
    <td>Documentation</td>
    <td>
      [How to Add to this Documentation](developer-how-tos_documentation.html)<br/>
      This page describes how to add to the documentation for this project. 
      This includes forking and cloning the project from Github, 
      getting started using R Markup (Rmd), 
      editing and previewing a new page, 
      and committing the updated documentation back up to Github.  
    </td>
  </tr>
  <!--
  *
  * How to Create a New AWS Instance
  *
  * -->
  <tr>
    <td>AWS</td>
    <td>
      <a href="developer-how-tos_aws_setup.html">
        How to Create a New Amazon Web Services (AWS) Instance
      </a>
      <br/>
      AWS provides free tier services and the ability to create a free AWS account. 
      This guide will walk through the process to do this. 
    </td>
  </tr>
  <!--
  *
  * How to Create a New Databricks Instance
  *
  * -->
  <tr>
    <td>Databricks</td>
    <td>
      <a href="developer-how-tos_databricks-create-new-instance.html">
        How to Create a New Databricks Instance
      </a>
      <br/>
      Databricks provides a 14 day trial version of Databricks. 
      This free version will require a host such as AWS, Azure, or Google Cloud. 
      This documentation uses AWS but should be vaild for the most part for Azure and Google Cloud. 
    </td>
  </tr>
  <!--
  *
  * Create a Databricks Token
  *
  * -->
  <tr>
    <td>Databricks</td>
    <td>
      <a href="developer-how-tos_databricks-token.html">Create a Databricks Token</a>
      <br/>
      Use this guide to create a Databricks token. 
      This token will be used as a password for the URL we will use to connect to our Databricks instance using JDBC.
    </td>
  </tr>
  <!--
  *
  * Getting Started with JDBC
  *
  * -->
  <tr>
    <td>Databricks</td>
    <td>
      <a href="developer-how-tos_databricks-jdbc.html">Getting Started with JDBC</a>
      <br/>
      This guide shows where to find and how to use the JDBC connection string and other resources required to connect to Databricks using JDBC.
    </td>
  </tr>
  <!--
  *
  * Enable DBFS
  *
  * -->
  <tr>
    <td>Databricks</td>
    <td>
      <a href="developer-how-tos_databricks-enable-dbfs.html">Enable DBFS</a>
      <br/>
      By default, Databricks does not enable file browsing. 
      We will want to browse the files we upload to make sure we've uploaded what we think we've uploaded. 
      This guide shows how to enable file browsing. 
    </td>
  </tr>
  <!--
  *
  * OHDSI on Databricks (Introduction and Documentation)
  *
  * -->
  <tr>
    <td><nobr>OHDSI<br/>Documentation</td>
    <td>
    <a href="./developer-how-tos_ohdsi-on-databricks.html">OHDSI on Databricks (Introduction and Documentation)</a>
    <br/>
      This document gives and introduction and background on how to create a complete OHDSI on Databricks implementation. 
      This can be used to create a demo CDM instance, or to connect an existing CDM instance (e.g. from your elt process). 
      The implementation described here does not use Docker/Broadsea 
      and assumes that you have installed basic development/implementation software 
      such as Java and PostgreSql. 
    </td>
  </tr>
  <!--
  *
  * OHDSI on Databricks (Standalone Implementation Guide)
  *
  * -->
  <tr>
    <td><nobr>OHDSI<br/>Standalon&nbsp;(Tomcat)</td>
    <td>
    <a href="./developer-how-tos_ohdsi-on-databricks_quickstart-guide.html">OHDSI on Databricks (Standalone Implementation Guide)</a>
    <br/>
      This quick start guide describes how to set up and instance of the OHDSI stack using a standalone Tomcat instance (i.e. not Broadsea). 
    </td>
  </tr>
  <!--
  *
  * Broadsea on Databricks
  *
  * -->
  <tr>
    <td><nobr>OHDSI<br/>Broadsea</td>
    <td>
      <a href="./developer-how-tos_broadsea.html">Broadsea on Databricks Implementation Guide</a>
      <br/>
      This document describes how to standup OHDSI on Databricks using 
      <a href="https://github.com/OHDSI/Broadsea">Broadsea</a>.
    </td>
  </tr>
  <!--
  *
  * OHDSI on Databricks Configuration Notes
  *
  * -->
  <tr>
    <td><nobr>OHDSI<br/>Configuration&nbsp;Notes</td>
    <td>
      <a href="./developer-how-tos_ohdsi-on-databricks-url.html">OHDSI on Databricks Configuration Notes</a>
      <br/>
      This document describes details on configuration required for a successful deployment of OHDSI on Databricks 
      including details on the JDBC URL, Parameterization of the JDBC Token, UseNativeQuery, SocketTimeout, and SSL configuration. 
    </td>
  </tr>
  <!--
  *
  * Blank row (to give line at the bottom of the table)
  *
  * -->
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>
  
  
  
  
