---
title: '<div>How to Run a Strategus study</div>'
output:
  html_document:
    toc: TRUE
    toc_depth: 3
    toc_float:
      collapsed: FALSE
---

<!--
*
* HOW TO: Import and Export Concept Sets
*
--> 

<!--
*
* Introduction
*
-->

<h2>Introduction</h2>
This document provides a complete example of how to run a Strategus study. 

<!--
*
* Identify CDM data source
*
-->

<h2>Identify or create CDM</h2>
Before starting, identify the datasource to be used as the CDM. 
If you do not have a data source, 
you can create an instance of the Eunomia CDM 
by following the instructions in the 
<a href="./developer-how-tos_ohdsi-on-databricks.html">OHDSI on databricks guide</a> 
in the "Create a test instance of the CDM in Databricks" section.  

<!--
*
* Installation of R and RTools
*
-->

<h2>Installation of R and RTools</h2>
R 4.2.3 and RTools 4.2 are used here. 
These are the versions that were used for testing and validation. 
R 4.2.3 can be downloaded from 
<a href="https://cran.r-project.org/bin/windows/base/">https://cran.r-project.org/bin/windows/base/</a>. 
<br/>
<br/>
RTools 4.2 can be downloaded from 
<nobr><a href="https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html">https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html</a></nobr> 
<br/>
<br/>
Or the windows installer for each can be directly downloaded here:
<ul>
  <li>
    <a download href="https://www.dropbox.com/scl/fi/2ao0wbi49ic19jcxk8lf0/R-4.2.3-win.exe?rlkey=3qlk90ugzx7q9ym2z3yjqmhl5&dl=1">R 4.2.3</a>
  </li>
  <li>
    <a download href="https://www.dropbox.com/scl/fi/1xi8asmak0u6foi6b5mgc/rtools42-5355-5357.exe?rlkey=r0psxd9e5gv1vk8rkm7pasmad&dl=1">RTools 4.2</a>
  </li>
</ul>
Run the R installer executable.  
Set the LibPath as described below.  
Then run the RTools installer.  

<!--
*
* Set LibPaths
*
-->

<h2>Set LibPaths</h2>
Strategus uses the .libPaths() setting shown below. 
In order for libriaries to all be placed in the correct place, 
the default for .libPaths() needs to be set. 
Edit the .Renviron file by running the following.  
<pre class="r">
install.packages("usethis")
library(usethis)
edit_r_environ()
</pre>
Add the following line to your .Renviron file.  
<pre class="r">
R_LIBS_USER="C:/Program Files/R/R-4.2.3/library"
</pre>


